### ISSUE TITLE
Handshake needs to establish a round-trip network overhead

### ISSUE THREAD

**Issue by mmm8955405** [davedoesdev/bpmux#5]
Handshake needs to establish a round-trip network overhead. I hope to change it to http2, and each connection has its own ID. The underlying network has been established and there is no need to shake hands at a time. You shake hands like this, which is an extra network overhead. This is very bad

**Comment by davedoesdev** [comment]
Hi @mmm8955405 -thanks for your question. Are you using Node.js at both sides of your system?

**Comment by mmm8955405** [comment]
> Hi @mmm8955405 -thanks for your question. Are you using Node.js at both sides of your system? If you are, you don't need bpmux when using http2 because Node itself will do the multiplexing using streams.

I use multiplexing on websocket. What I want to say is that you shouldn't set up a handshake, which is a lot of network overhead. You should bring your own ID for each data. The multiplexing of http2 is to bring an ID to each request. I hope you can modify it as soon as possible.

**Comment by davedoesdev** [comment]
@mmm8955405 I'm still not quite sure I follow. Is the problem that bpmux waits for the handshake response before sending data?
The handshake is needed for backpressure to inform how much space is available at the other side.
It maybe be possible, however, to provide an option to set the remote free space to something other than zero initially.

**Comment by mmm8955405** [comment]
@davedoesdev 
I'm a server engineer, and none of the popular open source transport protocols I've seen need to shake hands again.

I took the time to look at how bpmux works. The idea of shaking hands and trying to get remote state is not good.

I think a general reuse protocol should be like this:

1. Has a header field to control which channel (such as ID)

2. The length of each header field should state what it is used for. This is crucial. For other programming languages, the reuse protocol can be implemented again.

But I didn't see it at all in bpmux.

It's true that bpmux is convenient. But in any case, you should not continue shaking hands on an existing connection.

So I hope you can modify the project, because I don't see other nodejs open source projects doing general multiplexing protocol

At present, I don't know much about the way nodejs's steam works. So I can't solve the back pressure you mentioned. You can also create a new duplex stream for each channel, triggering readability if it is the same channel

**Comment by davedoesdev** [comment]
@mmm8955405 thanks for your feedback - interesting and I appreciate it.

I wrote bpmux to give backpressure on each multiplex streams rather than just the underlying carrier stream. Without it you can flood the receiver, but you do pay an overhead for sure. The way I implemented it was to get each stream to say how much the receiver has read from it. 

1. The channel ID is in the second byte of each message: https://github.com/davedoesdev/bpmux/blob/master/index.js#L769 and the type is in the first byte.

2. bpmux uses frame-stream to chunk messages, which handles the length.

If you don't need backpressure, https://github.com/maxogden/multiplex should suffice. See [here](https://github.com/davedoesdev/bpmux#comparison) for a comparison of backpressure between the two projects.

For http2, Nodejs to Nodejs, you can just use the built-in support and create multiple streams per session. Http2 supports prioritization of its multiplexed streams, which can be used to stop one stream starving the others.
